<?php 
    echo "    
        <footer>
            <p>Dang Nam Khanh, Le Xuan Nhat, Duong Quang Thanh</p>
            <p>Copyright &copy; 2023 Señor Ropa. All rights Reserved</p>
            <p>Menu icon by <a class='credit' href='https://www.iconfinder.com/icons/1891012/blue_cercle_hamburger_list_mavigation_menu_stack_icon'>iconfinder.com</a> and background image by <a class='credit' href='https://www.wallpaperflare.com/pc-build-water-cooling-ram-120mm-fan-wallpaper-ysbod'>Wallpaper Flare</a>
        </footer>";
?>