<?php
    echo "
    <header>

		<h1>PC Señor</h1>

		<nav>
			<input type='checkbox' id='button'>
			<label for='button'><img src='images/nav.png' alt='navbar'></label>
			<ul class='nav'>
				<li><a href='index.php'>Index</a></li>
				<li><a href='product.php'>Products</a></li>
				<li><a href='about.php'>About</a></li>
				<li><a href='enhancements2.php'>Enhancements</a></li>
				<li><a href='login.php'>Manager</a></li>
			</ul>
		</nav>

	</header>";
?>